### ISSUE TITLE
lat_lon 为空

### ISSUE THREAD

**Issue by yuan-web** [tomhaoye/crawler.58#1]
![20180920084433](https://user-images.githubusercontent.com/11371158/45789213-11e12080-bcb1-11e8-9f0d-d902ae75ca8e.png)

大佬，爬取的经纬度为空

**Comment by tomhaoye** [comment]
@yuan-web 全部数据的经纬度都空吗？有可能部分地区页面结构问题，也可能是页面结构改了。今晚我看一下

**Comment by tomhaoye** [comment]
@yuan-web 那个api接口加了访问次数限制了，恐怕要上代理才能继续爬了

**Comment by tomhaoye** [comment]
@yuan-web 应该是加了访问频率限制，恐怕要上代理才行了

**Comment by yuan-web** [comment]
@tomhaoye 经纬度都是空，但是数据都获取到了，所以不是访问限制，应该是匹配经纬度那里有点问题

**Comment by tomhaoye** [comment]
详细信息和经纬度都是通过 detail.py 获取的，这文件访问的是58手机端的详情页面，你可以执行一遍之后找一个手机端详情页面去访问一下，是需要用通过滑动图片验证码才能访问的，节后我再去弄一下吧～

@yuan-web

**Comment by tomhaoye** [comment]
@yuan-web 额，你这个是长沙的数据吧，我执行了一把，发现没问题，你是不是忘了执行`python detail.py cs`？另外58的验证码似乎只会出现一次，遇到了随便打开一个小区页面`http://m.58.com/xiaoqu/chunshuian/`手动通过之后就可以继续了。我也写了模拟绕过验证码的代码，完善后可能会加进去，但是需要很多额外的库和selenium webdriver。
![123](https://user-images.githubusercontent.com/11913766/46254576-03221700-c4c4-11e8-9a8c-796e9936f979.png)
